// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMyReRDIoU5Ahu5nvr__oON_nPMXSj1mk',
    appId: '1:1053821541115:web:424affac2e85e8b1396e5e',
    messagingSenderId: '1053821541115',
    projectId: 'shop-paradise-demo',
    authDomain: 'shop-paradise-demo.firebaseapp.com',
    storageBucket: 'shop-paradise-demo.firebasestorage.app',
    measurementId: 'G-3RNHTR8SPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBmHteEmxYMvsemzHRBImBfU6GosV-kmQ',
    appId: '1:1053821541115:android:f9e9987dd4b5e3b3396e5e',
    messagingSenderId: '1053821541115',
    projectId: 'shop-paradise-demo',
    storageBucket: 'shop-paradise-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbv0JyCGoFPTppH2RvpT56QsOxFqEn9s',
    appId: '1:1053821541115:ios:477be0f4e6098f3f396e5e',
    messagingSenderId: '1053821541115',
    projectId: 'shop-paradise-demo',
    storageBucket: 'shop-paradise-demo.firebasestorage.app',
    iosBundleId: 'com.example.shopParadiseKz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATbv0JyCGoFPTppH2RvpT56QsOxFqEn9s',
    appId: '1:1053821541115:ios:477be0f4e6098f3f396e5e',
    messagingSenderId: '1053821541115',
    projectId: 'shop-paradise-demo',
    storageBucket: 'shop-paradise-demo.firebasestorage.app',
    iosBundleId: 'com.example.shopParadiseKz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMyReRDIoU5Ahu5nvr__oON_nPMXSj1mk',
    appId: '1:1053821541115:web:3787280a458f74a5396e5e',
    messagingSenderId: '1053821541115',
    projectId: 'shop-paradise-demo',
    authDomain: 'shop-paradise-demo.firebaseapp.com',
    storageBucket: 'shop-paradise-demo.firebasestorage.app',
    measurementId: 'G-6K6X3W69FE',
  );
}
